on: [push]

jobs:
  docker_build_job:
    runs-on: ubuntu-latest
    name: "Docker Build"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Push
        uses: mr-smithers-excellent/docker-build-push@github-registry
        with:
          image: rainbow-options/rainbow-options
          registry: docker.pkg.github.com
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
